#
# this is the configuration loaded by the new parts of the registration system frontend code
#
web:
  # must include trailing slash
  server_url: 'http://localhost:10000/'
  # must NOT include leading or trailing slashes
  context_path: 'regsys'
downstream:
  auth_service: 'http://localhost:4712'
  attendee_service: 'http://localhost:9091'
  payment_service: 'http://localhost:9092'
  mail_service: 'http://localhost:9093'
  token_cookie_name: 'JWT'
  api_token: 'api-token-must-be-pretty-long'
  nosecounter_token: 'nosecounter-test-token'
  dd_token: 'localtoken'
  secu_token: 'localtoken'
  secu_secret: 'localsecret'
testing: {}
  #
  # uncomment and fill with valid tokens to have an easy way to log in on localhost - NEVER configure in production
  #
  # admin_token: 'eyJhbG...'
  # staff_token: 'eyJhbG...'
  # user_token: 'eyJhbG...'
choices:
  flags:
    hc:
      description: 'Wheelchair'
      help_url: 'help/opt_wheelchair.html'
    anon:
      description: 'Legal Name is Confidential'
      help_url: 'help/opt_anonymous.html'
    ev:
      description: 'Eurofurence e.V. Member'
      help_url: 'help/opt_member.html'
    guest:
      description: 'Guest of the Convention'
      help_url: 'help/guest.html'
      admin_only: true
    skip_ban_check:
      description: 'Bypass ban check for this attendee'
      help_url: 'help/skip_ban_check.html'
      admin_only: true
  packages:
    room-none:
      description: 'No Room'
      help_url: 'help/room_none.html'
      vat_percent: 7
      default: true
      read_only: true
    attendance:
      description: 'Entrance Fee (Convention Ticket)'
      help_url: 'help/fee_basic.html'
      price_early: 9500
      price_late: 11000
      price_atcon: 13500
      vat_percent: 19
      default: true
      read_only: true
    stage:
      description: 'Entrance Fee (Stage Ticket)'
      help_url: 'help/fee_stage.html'
      price_early: 500
      price_late: 500
      price_atcon: 500
      vat_percent: 19
      default: true
      read_only: true
    sponsor:
      description: 'Sponsor Upgrade'
      help_url: 'help/fee_sponsor.html'
      price_early: 6500
      price_late: 6500
      price_atcon: 6500
      vat_percent: 19
    sponsor2:
      description: 'Supersponsor Upgrade'
      help_url: 'help/fee_sponsor2.html'
      price_early: 16000
      price_late: 16000
      price_atcon: 16000
      vat_percent: 19
      constraint: '!sponsor'
      constraint_msg: 'Please choose only one of Sponsor or Supersponsor.'
    day-thu:
      description: 'Day Guest (Thursday)'
      help_url: 'help/fee_day_thu.html'
      price_early: 7000
      price_late: 7000
      price_atcon: 7000
      vat_percent: 19
      read_only: true
      constraint: '!attendance,!stage'
      constraint_msg: 'Must disable Convention Ticket and Stage Ticket for Day Guests.'
    day-fri:
      description: 'Day Guest (Friday)'
      help_url: 'help/fee_day_fri.html'
      price_early: 7000
      price_late: 7000
      price_atcon: 7000
      vat_percent: 19
      read_only: true
      constraint: '!attendance,!stage'
      constraint_msg: 'Must disable Convention Ticket and Stage Ticket for Day Guests.'
    day-sat:
      description: 'Day Guest (Saturday)'
      help_url: 'help/fee_day_sat.html'
      price_early: 7000
      price_late: 7000
      price_atcon: 7000
      vat_percent: 19
      read_only: true
      constraint: '!attendance,!stage'
      constraint_msg: 'Must disable Convention Ticket and Stage Ticket for Day Guests.'
  options:
    art:
      description: 'Artist'
      help_url: 'help/opt_artist.html'
    anim:
      description: 'Animator'
      help_url: 'help/opt_animator.html'
    music:
      description: 'Musician'
      help_url: 'help/opt_musician.html'
    suit:
      description: 'Fursuiter'
      help_url: 'help/opt_fursuiter.html'
tshirtsizes:
  - 'XS'
  - 'wXS'
  - 'S'
  - 'wS'
  - 'M'
  - 'wM'
  - 'L'
  - 'wL'
  - 'XL'
  - 'wXL'
  - 'XXL'
  - 'wXXL'
  - '3XL'
  - 'w3XL'
  - '4XL'
  - 'w4XL'
spoken_languages:
  - 'en_US'
  - 'de_DE'
registration_languages:
  - 'en_US'
countries:
  - 'AF'
  - 'AN'
  - 'AX'
  - 'AL'
  - 'DZ'
  - 'AS'
  - 'AD'
  - 'AO'
  - 'AI'
  - 'AQ'
  - 'AG'
  - 'AR'
  - 'AM'
  - 'AW'
  - 'AU'
  - 'AT'
  - 'AZ'
  - 'BS'
  - 'BH'
  - 'BD'
  - 'BB'
  - 'BY'
  - 'BE'
  - 'BZ'
  - 'BJ'
  - 'BM'
  - 'BT'
  - 'BO'
  - 'BQ'
  - 'BA'
  - 'BW'
  - 'BV'
  - 'BR'
  - 'IO'
  - 'BN'
  - 'BG'
  - 'BF'
  - 'BI'
  - 'CV'
  - 'KH'
  - 'CM'
  - 'CA'
  - 'KY'
  - 'CF'
  - 'TD'
  - 'CL'
  - 'CN'
  - 'CX'
  - 'CC'
  - 'CO'
  - 'KM'
  - 'CG'
  - 'CD'
  - 'CK'
  - 'CR'
  - 'CI'
  - 'HR'
  - 'CU'
  - 'CW'
  - 'CY'
  - 'CZ'
  - 'DK'
  - 'DJ'
  - 'DM'
  - 'DO'
  - 'EC'
  - 'EG'
  - 'SV'
  - 'GQ'
  - 'ER'
  - 'EE'
  - 'SZ'
  - 'ET'
  - 'FK'
  - 'FO'
  - 'FJ'
  - 'FI'
  - 'FR'
  - 'GF'
  - 'PF'
  - 'TF'
  - 'GA'
  - 'GM'
  - 'GE'
  - 'DE'
  - 'GH'
  - 'GI'
  - 'GR'
  - 'GL'
  - 'GD'
  - 'GP'
  - 'GU'
  - 'GT'
  - 'GG'
  - 'GN'
  - 'GW'
  - 'GY'
  - 'HT'
  - 'HM'
  - 'VA'
  - 'HN'
  - 'HK'
  - 'HU'
  - 'IS'
  - 'IN'
  - 'ID'
  - 'IR'
  - 'IQ'
  - 'IE'
  - 'IM'
  - 'IL'
  - 'IT'
  - 'JM'
  - 'JP'
  - 'JE'
  - 'JO'
  - 'KZ'
  - 'KE'
  - 'KI'
  - 'KP'
  - 'KR'
  - 'KW'
  - 'KG'
  - 'LA'
  - 'LV'
  - 'LB'
  - 'LS'
  - 'LR'
  - 'LY'
  - 'LI'
  - 'LT'
  - 'LU'
  - 'MO'
  - 'MG'
  - 'MW'
  - 'MY'
  - 'MV'
  - 'ML'
  - 'MT'
  - 'MH'
  - 'MQ'
  - 'MR'
  - 'MU'
  - 'YT'
  - 'MX'
  - 'FM'
  - 'MD'
  - 'MC'
  - 'MN'
  - 'ME'
  - 'MS'
  - 'MA'
  - 'MZ'
  - 'MM'
  - 'NA'
  - 'NR'
  - 'NP'
  - 'NL'
  - 'NC'
  - 'NZ'
  - 'NI'
  - 'NE'
  - 'NG'
  - 'NU'
  - 'NF'
  - 'MK'
  - 'MP'
  - 'NO'
  - 'OM'
  - 'PK'
  - 'PW'
  - 'PS'
  - 'PA'
  - 'PG'
  - 'PY'
  - 'PE'
  - 'PH'
  - 'PN'
  - 'PL'
  - 'PT'
  - 'PR'
  - 'QA'
  - 'RE'
  - 'RO'
  - 'RU'
  - 'RW'
  - 'BL'
  - 'SH'
  - 'KN'
  - 'LC'
  - 'MF'
  - 'PM'
  - 'VC'
  - 'WS'
  - 'SM'
  - 'ST'
  - 'SA'
  - 'SN'
  - 'RS'
  - 'SC'
  - 'SL'
  - 'SG'
  - 'SX'
  - 'SK'
  - 'SI'
  - 'SB'
  - 'SO'
  - 'ZA'
  - 'GS'
  - 'SS'
  - 'ES'
  - 'LK'
  - 'SD'
  - 'SR'
  - 'SJ'
  - 'SE'
  - 'CH'
  - 'SY'
  - 'TW'
  - 'TJ'
  - 'TZ'
  - 'TH'
  - 'TL'
  - 'TG'
  - 'TK'
  - 'TO'
  - 'TT'
  - 'TN'
  - 'TR'
  - 'TM'
  - 'TC'
  - 'TV'
  - 'UG'
  - 'UA'
  - 'AE'
  - 'GB'
  - 'US'
  - 'UM'
  - 'UY'
  - 'UZ'
  - 'VU'
  - 'VE'
  - 'VN'
  - 'VG'
  - 'VI'
  - 'WF'
  - 'EH'
  - 'YE'
  - 'ZM'
  - 'ZW'
  - 'XK'
